name: Deploy Preview

on:
  push:
    branches:
      - develop
      - feature/**
      - fix/**
      - refactor/**

jobs:
  run-build:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: >-
            ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DASHBOARD_VITE_TAILWIND_RADIX
            }}
          channelId: live
          projectId: dashboard-vite-tailwind-radix
